// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'dart:developer';

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        log("Android Platform");
        return android;
      case TargetPlatform.iOS:
        log("IOS Platform");
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxhxjh5VIx7g1mZfDRQulvCIFCtjBx8Y',
    appId: '1:426859956024:android:b116f8006b14263d8ba3cd',
    messagingSenderId: '426859956024',
    projectId: 'chat-bot-d1401',
    storageBucket: 'chat-bot-d1401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_hRrvcgsve7zahpIv81CS8cdzmFJni0Q',
    appId: '1:426859956024:ios:0af4c81ac4aba40e8ba3cd',
    messagingSenderId: '426859956024',
    projectId: 'chat-bot-d1401',
    storageBucket: 'chat-bot-d1401.firebasestorage.app',
    iosBundleId: 'com.example.chatBot',
  );
}
